[BE-4893]: Fixed error and warning messages, and wrong logic for vers…
appcircleio/appcircle-ios-build-version-increment pull request #7
Opened 2024-11-26 10:25 UTC by boztopuz

…ion increment strategy.

2025-05-30 12:37 UTC, ftmzhrsckldr requested changes

2025-06-03 13:28 UTC, boztopuz commented on main.rb
> +    puts "Directly updating 'Info.plist' with the value: '#{build_number}'."
Actually, it can be blue because this is information. I will update

2025-06-03 13:28 UTC, boztopuz commented on main.rb
> +    puts "Build number updated to: #{current_build_number}".blue if build_number_source
next_build_number is holds the final version and build number codes, this mean is these variables comes from user. current_build_number parameter comes from project and these parameters are being updated and used instead of next_build_number

2025-06-03 13:28 UTC, boztopuz commented on main.rb
> +    puts "Version number updated to: #{current_version_number}".blue if version_number_source
next_build_number is holds the final version and build number codes, this mean is these variables comes from user. current_build_number parameter comes from project and these parameters are being updated and used instead of next_build_number

2025-06-03 13:28 UTC, boztopuz commented on main.rb
> +  exit 1
I will change this feedback

2025-06-05 08:33 UTC, ftmzhrsckldr commented on main.rb
> +    puts "Version number updated to: #{current_version_number}".blue if version_number_source
Just below this code, `next_version_number` is assigned as AC environment variable. The ENV to which the assignment is made should be logged.

```
    open(ENV['AC_ENV_FILE_PATH'], 'a') { |f|
      f.puts "AC_IOS_NEW_BUILD_NUMBER=#{next_build_number}"
      f.puts "AC_IOS_NEW_VERSION_NUMBER=#{next_version_number}"
    }
```

2025-06-05 08:37 UTC, ftmzhrsckldr requested changes

2025-06-05 08:37 UTC, ftmzhrsckldr commented on main.rb
> +      f.puts "AC_IOS_NEW_VERSION_NUMBER=#{next_version_number}"
This code works incorrectly. 
If the user has selected a build number but not a version code, it will assign `nil` as `AC_IOS_NEW_VERSION_NUMBER`.

2025-06-05 08:37 UTC, ftmzhrsckldr commented on main.rb
> +      f.puts "AC_IOS_NEW_BUILD_NUMBER=#{next_build_number}"
This code works incorrectly. 
If the user has selected a version code but not a build number, it will assign `nil` as `AC_IOS_NEW_BUILD_NUMBER`.

2025-06-05 08:38 UTC, ftmzhrsckldr commented on main.rb
> +    abort("Error: No version or build number source specified. Please set the version or build number in the Build Configuration.".red)
But in this case, every user who has not created a new workflow and has not configured an increment version will get an error, is that correct?

2025-07-02 08:02 UTC, ftmzhrsckldr approved these changes

2025-07-02 08:02 UTC, merged